version: 0.2

env:
  variables:
    SECRET_ID: "locality-ui-dev"

phases:
  install:
    commands:
      - echo "Updating system and installing dependencies..."
      - apt update && apt install -y jq curl

      - echo "Installing NVM and setting up Node.js v20.15.1..."
      - curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      - |
        export NVM_DIR="$HOME/.nvm"
        echo "NVM_DIR is set to $NVM_DIR"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        nvm install 20.15.1
        nvm use 20.15.1
        nvm install-latest-npm
        echo "Node.js version: $(node -v)"

      - echo "Installing AWS CLI and dependencies..."
      - npm install -g aws-cli
      - npm install

  pre_build:
    commands:
      - echo "Fetching secrets from AWS Secrets Manager..."
      - |
        SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "$SECRET_ID" --query SecretString --output text)
        echo "Secrets retrieved successfully."

        echo "$SECRET_JSON" | jq -r 'to_entries | .[] | "export \(.key)=\(.value)"' >> /tmp/secrets_env.sh
        . /tmp/secrets_env.sh

      - echo "Loaded environment variables from Secrets Manager, using $ENVIRONMENT environment"

  build:
    commands:
      - echo "Building the Angular project..."
      - npm run build
      - echo "Syncing the entire dist folder to S3..."
      - ENV_FOLDER=DEV
      - aws s3 sync dist s3://$S3_BUCKET/$ENV_FOLDER --delete

  post_build:
    commands:
      - echo "Generating and deploying Lambda@Edge function..."
      - |
        cat <<EOF > lambda-edge.js
        'use strict';
        exports.handler = async (event) => {
            return {
                status: '200',
                statusDescription: 'OK',
                headers: {
                    'content-type': [{ key: 'Content-Type', value: 'application/javascript' }],
                    'cache-control': [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }]
                },
                body: \`$(cat public/assets/env.example.js)\`
            };
        };
        EOF
      - zip lambda-edge.zip lambda-edge.js

      # Check if Lambda function exists
      - |
        if aws lambda get-function --function-name $LAMBDA_FUNCTION_NAME >/dev/null 2>&1; then
          echo "Updating existing Lambda function..."
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda-edge.zip
        else
          echo "Creating new Lambda function..."
          aws lambda create-function --function-name $LAMBDA_FUNCTION_NAME \
            --runtime nodejs18.x \
            --role $LAMBDA_ROLE_ARN \
            --handler lambda-edge.handler \
            --zip-file fileb://lambda-edge.zip \
            --region us-east-1
          sleep 10  # Allow time for Lambda function to become active
        fi

      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - "**/*"
